spring.application.name=Test
server.port=8081
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f604ffeb26bcd0
spring.mail.password=fd1677e3423278
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true